# Site
repository: chrmits/myCV
favicon: images/favicon.ico

# Personal info
name: Christos Mitsianis
title: Photography tutor, audiovisual & new media creator
email: chr.mits@gmail.com
website: www.namaproject.gr

# Social links
# twitter_username: chmits
github_username:  chrmits
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: c.mits
linkedin_username: chmits
# pinterest_username: jekyll
youtube_username: Chmits
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Christos Mitsianis,

  I am photography <mark>tutor</mark> and audiovisual & new media arts <mark>creator</mark> with innovative ideas.
   - web - interactive documentary
   - video art
   - photography
   - interdisciplinary research ideas
   - computer science

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in arts and information technology some of my other interests and hobbies are:
   - Mandolin and music
   - Dancing salsa
   - Astronomy
   - Walking and researching relationships between spaces and emotions

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
